In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("TalentAI environment is ready!")

TalentAI environment is ready!

In [3]:
project_goal = """
TalentAI is an AI-powered recruitment intelligence platform.

The system will analyze job and candidate data to:
1. Understand candidate profiles.
2. Match candidates with job requirements.
3. Identify missing skills.
4. Predict recruitment-related outcomes using machine learning.
5. Provide AI-powered insights for recruiters.
"""

print(project_goal)

TalentAI is an AI-powered recruitment intelligence platform.

The system will analyze job and candidate data to:
1. Understand candidate profiles.
2. Match candidates with job requirements.
3. Identify missing skills.
4. Predict recruitment-related outcomes using machine learning.
5. Provide AI-powered insights for recruiters.

In [4]:
from datasets import load_dataset

dataset = load_dataset(
    "lang-uk/recruitment-dataset-candidate-profiles-english"
)

print(dataset)

e:\TalentAI\.venv-1\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
e:\TalentAI\.venv-1\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Asmaa Ahmed\.cache\huggingface\hub\datasets--lang-uk--recruitment-dataset-candidate-profiles-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
e:\TalentAI\.venv-1\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Asmaa Ahmed\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 210250/210250 [00:04<00:00, 43050.77 examples/s]

DatasetDict({
    train: Dataset({
        features: ['Position', 'Moreinfo', 'Looking For', 'Highlights', 'Primary Keyword', 'English Level', 'Experience Years', 'CV', 'CV_lang', 'id', '__index_level_0__'],
        num_rows: 210250
    })
})

In [5]:
df = dataset["train"].to_pandas()

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 210250
Columns: 11

In [6]:
df.head()

,Position,Moreinfo,Looking For,Highlights,Primary Keyword,English Level,Experience Years,CV,CV_lang,id,__index_level_0__
0,"13 years of exp || Solidity, C#, JavaScript ||...",Who am I:\r\n- 13 years of commercial experien...,I am interested in:\r\n- part-time engagement;...,Landed a role of Director of Blockchain Develo...,Lead,fluent,11.0,Landed a role of Director of Blockchain Develo...,en,50534b61-6826-52b1-9ac5-bfd2cfa348ec,24230
1,1c Developer,Worked on a mobile application for tracking trips,NaN,NaN,Other,intermediate,3.0,\nWorked on a mobile application for tracking ...,en,c2b9ea56-b5c8-50ec-a63b-053a5c8ff467,24231
2,1C developer,1 am an 1C developer. I deployed an 1C to typo...,NaN,NaN,Flutter,intermediate,11.0,\n1 am an 1C developer. I deployed an 1C to ty...,en,b3bfe3ed-ec25-56b2-8aaa-8c629120538e,24232
3,1C Developer,Perfect knowledge of 1C:Enterprise Platform.\...,NaN,NaN,Other,intermediate,11.0,\nPerfect knowledge of 1C:Enterprise Platform...,en,163fb9a3-3695-5dc3-b1d0-e0038ce4d0a5,24233
4,#1 Customer Support Specialist,"Tech addicted, experienced customer support wi...",In terms of the nature of the Customer Support...,"thousands of resolved problems, also, thousand...",Support,fluent,2.5,"thousands of resolved problems, also, thousand...",en,3f201183-db58-5333-9139-74c16059dc4a,24234

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 210250 entries, 0 to 210249
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Position           210250 non-null  str
 1   Moreinfo           210250 non-null  str
 2   Looking For        102055 non-null  str
 3   Highlights         105529 non-null  str
 4   Primary Keyword    210207 non-null  str
 5   English Level      209765 non-null  str
 6   Experience Years   210250 non-null  float64
 7   CV                 210250 non-null  str
 8   CV_lang            210250 non-null  str
 9   id                 210250 non-null  str
 10  __index_level_0__  210250 non-null  int64
dtypes: float64(1), int64(1), str(9)
memory usage: 17.6 MB

In [8]:
df.shape

(210250, 11)

In [9]:
df.dtypes

Position                 str
Moreinfo                 str
Looking For              str
Highlights               str
Primary Keyword          str
English Level            str
Experience Years     float64
CV                       str
CV_lang                  str
id                       str
__index_level_0__      int64
dtype: object

In [10]:
df.isnull().sum()

Position                  0
Moreinfo                  0
Looking For          108195
Highlights           104721
Primary Keyword          43
English Level           485
Experience Years          0
CV                        0
CV_lang                   0
id                        0
__index_level_0__         0
dtype: int64

In [11]:
print("Positions:", df["Position"].nunique())
print("English Levels:", df["English Level"].nunique())
print("Primary Keywords:", df["Primary Keyword"].nunique())
print("CV Languages:", df["CV_lang"].nunique())

Positions: 52913
English Levels: 6
Primary Keywords: 41
CV Languages: 1

In [12]:
print(df["English Level"].value_counts())

English Level
upper           78146
intermediate    64915
fluent          43102
pre             18197
basic            5269
no_english        136
Name: count, dtype: int64

In [13]:
print(df["CV_lang"].value_counts())

CV_lang
en    210250
Name: count, dtype: int64

In [14]:
print(df["Experience Years"].describe())

count    210250.000000
mean          3.836901
std           3.291261
min           0.000000
25%           1.000000
50%           3.000000
75%           6.000000
max          11.000000
Name: Experience Years, dtype: float64

In [15]:
print("Duplicate IDs:", df["id"].duplicated().sum())
print("Duplicate CVs:", df["CV"].duplicated().sum())

Duplicate IDs: 0
Duplicate CVs: 0

In [16]:
missing = df.isnull().sum()

print(missing[missing > 0])

Looking For        108195
Highlights         104721
Primary Keyword        43
English Level         485
dtype: int64

In [17]:
df["Position"].value_counts().head(20)

Position
QA Engineer                   6908
Project Manager               6643
Front-end developer           5034
Junior QA Engineer            4940
Manual QA Engineer            3625
Java Developer                3607
UI/UX Designer                3569
Junior Front-end Developer    2946
Front-End Developer           2806
IT Recruiter                  2704
UX/UI Designer                2369
Python Developer              2233
Business Analyst              2132
Frontend Developer            1965
Full Stack Web Developer      1751
Senior Software Engineer      1723
Software Engineer             1681
.NET Developer                1584
Product manager               1572
iOS Developer                 1562
Name: count, dtype: int64

In [18]:
df["Primary Keyword"].value_counts(dropna=False)

Primary Keyword
JavaScript           33980
QA                   25089
Design               15068
Project Manager      12499
Java                 11463
.NET                  9388
Marketing             8984
Python                7588
PHP                   6947
QA Automation         5756
Other                 5395
Node.js               4896
Recruiter             4865
HR                    4776
Support               4597
Business Analyst      4431
DevOps                4120
Product Manager       4048
Sales                 3784
iOS                   3200
Android               3087
C++                   2981
Data Science          2571
Artist                2542
Lead                  2373
Data Analyst          2271
Unity                 1815
Sysadmin              1528
Ruby                  1380
Golang                1343
SQL                   1119
Flutter               1118
SEO                    875
Data Engineer          803
Lead Generation        799
Security               781
Technical Writing      687
Salesforce             380
Scala                  364
Scrum Master           356
Rust                   160
NaN                     43
Name: count, dtype: int64

In [19]:
df["CV_Length"] = df["CV"].str.len()

print(df["CV_Length"].describe())

count    210250.000000
mean        944.351505
std         677.435931
min           6.000000
25%         454.000000
50%         751.000000
75%        1235.000000
max        7372.000000
Name: CV_Length, dtype: float64

In [20]:
sample = df["CV"].sample(5, random_state=42)

for i, cv in enumerate(sample, 1):
    print(f"\n--- CV {i} ---")
    print(cv[:1500])

--- CV 1 ---
5 years experience of management. Became an owner and developer for 15 microservices (almost without help of others and after monolith) so had a lot of self education. Have been responsible for newly developed highload services (chat server for hundreds of thousand users as an example). Triple reducing of RAM using at one of projects. Several data migrations. CI/CD flow updating.
February 2017 – February 2022, Ning inc., Software Engineer.
Back-end developer in a company well known as a social
networks sites builder. Support, fixing and development of plenty of
different microservices in a variety of areas, creation of new ones.
Responsibility for almost all java back-end layer services in the
company in respect to stability, building, deployment, requirements
reviews, communications and solution findings. Task priority
evaluation, tech interviews, onboardings
August 2014 – January 2017, LLC “Miratech”,
Software Engineer.
Development and reengineering one of mobile operator's key
high-loaded products (marketing activities provisioning system).
Writing analytical documentation, communications, reverse
engineering, troubleshooting, refactoring.
Development of Electronic Medical Records system for Canadian
provinces, new functionality creation, integration with other systems.
Development of social application for surgery.
February 2013 – August 2014, LLC “R-Style Softlab
Kiev”, Team Leader.
Assigning tasks for group, decomposition, planning, load
balancing, p

--- CV 2 ---

I'm looking for my first job, so I don't have any commercial development experience yet.
During process of learning worked with technologies such as ReactJS, Redux, TypeScript, Ajax, SPA etc. For further growth in this direction, I'm looking for an opportunity to work on real-world tasks as part of a team of experienced developers.

My current project is Evolutionary Simulator. The project represents a field populated by bots. Bots can interact with environment, such as food, poisons, other bots and remains. Each bot has its own genetic, which determines bot's behavior and possibilities. During their lifetime, bots are reproducing and mutate which accounts for biodiversity.
You can see it's current state through my GitHub profile, cyberbiology repository.


--- CV 3 ---
Im looking for company where i can progress as a developer, getting working experience
My Experience:
 Made a pet project in which it was possible to create / change / delete data
about matches and players in the database in this pet project i used:
EF Core,SQL Server, UnitOfWork Pattern, AutoMapper framework , HTML.
 I am doing a Dota Market pet project in which I used authorization through the
Steam platform, in this pet project i used:
EF Core, SQL Server, Steam OpenID framework, Repository Pattern and
Specification Pattern, Unit tests, CI/CD .


--- CV 4 ---
For the past year, I have been actively studying JS, HTML, CSS, React, and Redux. I am eager to contribute to real projects and showcase my skills. I have a repository where I store my previous works, but I am always looking to push my limits.
Building react applications using JSX, hooks, router, class, and functional
components
Creating Pixel Perfect, responsive webpages based on Figma grid layout design
using HTML, CSS, SASS, and JS
Handling code reviews, investigating, reproducing, and fixing bugs
Setting up dev environment using VS Code, NPM, JSON, ESlint, etc., deploying
websites on GH-pages
Leading peers, providing code review, helping when stuck in chats and during one-to-one calls
Conducting onboarding webinars with mentors for new students
Hosting informal networking gatherings for students.


--- CV 5 ---
Completed training course at NetCracker Education Center at ONPU in the following: Java SE/EE programming and Oracle Databases.

Projects:
Departments – Rest web-service. Team project based on Spring Framework and Hibernate. Participated in:
Spring Data JPA, Server API (MVC, REST), CRUD implementation and configuration.

Web application – Organizer for planing your future schedule. (Used: mvn, Spring mvc, security, server-side validation, jdbc, dao, eav database, mail notification, cleaning db with pl\sql scheduller job, aop (logging, transactions), caching db result set).

Hakatone project – Greenhouse, project based on arduino Galileo Gen2 (Monitoring temperature and humidity, automatic watering etc).
OOP, AOP (basics)
Java (Core, Swing, JDBC, JUnit, Log4J, Guava Cache)
Template eng. (JSP, Freemaker)
Java EE basics (Servlet API, JPA, Hibernate ORM, Mail API)
Spring (MVC, Security, Mail, JDBC Template, Spring+Hibernate validation)
Android SDK, UI/UX basics.
DB: Oracle SQL, PL\SQL, Postgres, SQLite
VCS: Git, Perforce
Build systems: Maven, Gradle
HttpServer&Servlet container: Tomcat, Jetty
Familiar with: Javascript, JQuery, JSON, CSS, XML, HTML
Have a 6month experience with: C#, Unity
I am communicative and persistent person, who is looking forward to find a suitable opportunity to continue the career as a Java Developer.

In [21]:
short_cvs = df[df["CV_Length"] < 100]

print("CVs shorter than 100 characters:", len(short_cvs))
print(short_cvs[["Position", "CV"]].head(10))

CVs shorter than 100 characters: 1016
                 Position                                                 CV
1            1c Developer  \nWorked on a mobile application for tracking ...
69   2d animation (Spine)  .\n- 2d animation\r\n- Spine Animation \r\n- A...
194             2d artist  \ncharacter design, concept art, visual develo...
268             2d artist  \nI worked on comicbook projects \r\nCharacter...
516             2D Artist    \nPortfolio: behance -dot- net/midnightartime\n
831           3d animator  \nblender 3d, character animation courses, gim...
843           3D animator  \nrender location 3D Max(vray, corona), animat...
886             3d artist  \n3d artist - 1.5 years\r\nui/ux designer - 2....
895             3d artist  \n3dsMax, Maya, Substance Painter, Marmoset To...
905             3d artist  \nCreate characters, props and environments fo...

In [22]:
print("URLs:", df["CV"].str.contains(r"http|www\.", case=False, regex=True).sum())
print("HTML tags:", df["CV"].str.contains(r"<[^>]+>", regex=True).sum())
print("Newlines:", df["CV"].str.contains(r"[\r\n]", regex=True).sum())

URLs: 6941
HTML tags: 186
Newlines: 210250

In [23]:
#CLEANING

df["CV_Clean"] = (
    df["CV"]
    .str.replace(r"[\r\n]+", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

print(df[["CV", "CV_Clean"]].head(3).to_string())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     CV                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                CV_Clean
0  Landed a role of Director of Blockchain Development in a metaverse project in Feb, 2022\nWho am I:\r\n- 13 years of commercial experience as a software engineer (web projects, customers from Europe and US);\r\n- 5 years in roles of team lead, tech lead, architect (including coding);\r\n- constant learner (books, courses, youtube);\r\n- C1 (Advanced) level of English (IELTS General = 7/9);\r\n- tech languages: C#, JavaScript, Solidity;\r\n- ready to learn Rust/Go.\r\n\r\nWhat can I bring in:\r\n- develop your web/blockchain project from gathering requirements stage to deployment and maintenance;\r\n- build a team of highly qualified and responsible professionals;\r\n- build processes or improve existing ones;\r\n- design architectures, code features, perform code reviews and so on.\r\n\r\nWhat can I technically (in short):\r\n- С#: 12 years of exp; .Net Core, .Net 6, MS SQL, EF, Clean Architecture, anything related to web platforms;\r\n- JavaScript: 7 years of exp; Node.js, React.js, Angular;\r\n- Solidity: since March 2021; upgradeable, secure, metamorphic, ERC20, ERC721, ERC1155, EIP1967, diamonds, proxies, clones, beacons, play-to-earn, vulnerabilities, on-chain/off-chain data storage, oracles, push/pull, tests, deployment, Truffle, Hardhat, Ganache, Mocha, Chai, web3.js, ether.js, OpenZeppelin, IPFS;\r\n- Databases: MS SQL (and any relational), NoSQL (MongoDB);\r\n- CI/CD: GitLab, TeamCity, BitBucket, Azure CI/CD Pipelines, GitHub Actions.\nI am interested in:\r\n- part-time engagement;\r\n- blockchain projects (DeFi, NFT, Gaming, Metaverse);\r\n- high salary (I apply to jobs paid $120+ per hour);\r\n- roles of a researcher and/or a leader rather than just coder;\r\n- ability to work remotely from Bali (with that said, I'm ok with visiting office during initial months to earn your respect and trust);\r\n- freedom in taking decisions;\r\n- time zone of Europe or Asia;\r\n- 1-2 interviews as a max, with tech specialists and managers.\r\n\r\nI am not interested in:\r\n- US time zone (I'd prefer morning shifts starting at 7am rather than coding till midnight);\r\n- strict "fabric" schedule like "9-to-6", "10-to-7", "11-to-8" and so on (since in IT this is an indicator of the unprofessional nature of the team and management);\r\n- jobs with a requirement of overall experience in software development of just a few years (I have 12, and the job offered should be my next challenge);\r\n- calls with HRs for "just to have a 30 minutes blah-blah-blah" (I have a prepared list of questions, and I hope you have prepared too);\r\n- if I have no word from you at any of the stages for more than a week - I am not more interested in the job;\r\n- I may consider test tasks only for tech lead or CTO roles, and it should be prepaid (for free you may have a look at my github and linkedin).  Landed a role of Director of Blockchain Development in a metaverse project in Feb, 2022 Who am I: - 13 years of commercial experience as a software engineer (web projects, customers from Europe and US); - 5 years in roles of team lead, tech lead, architect (including coding); - constant learner (books, courses, youtube); - C1 (Advanced) level of English (IELTS General = 7/9); - tech languages: C#, JavaScript, Solidity; - ready to learn Rust/Go. What can I bring in: - develop your web/blockchain project from gathering requirements stage to deployment and maintenance; - build a team of highly qualified and responsible professionals; - build processes or improve existing ones; - design architectures, code features, perform code reviews and so on. What can I technically (in short): - С#: 12 years of exp; .Net Core, .Net 6, MS SQL, EF, Clean Architecture, anything related to web platforms; - JavaScript: 7 years of exp; Node.js, React.js, Angular; - Solidity: since March 2021; upgradeable, secure, metamorphic, ERC20, ERC721, ERC1155, EIP1967, diamonds, proxies, clones, beacons, play-to-earn, vulnerabilities, on-chain/off-chain data storage, oracles, push/pull, tests, deployment, Truffle, Hardhat, Ganache, Mocha, Chai, web3.js, ether.js, OpenZeppelin, IPFS; - Databases: MS SQL (and any relational), NoSQL (MongoDB); - CI/CD: GitLab, TeamCity, BitBucket, Azure CI/CD Pipelines, GitHub Actions. I am interested in: - part-time engagement; - blockchain projects (DeFi, NFT, Gaming, Metaverse); - high salary (I apply to jobs paid $120+ per hour); - roles of a researcher and/or a leader rather than just coder; - ability to work remotely from Bali (with that said, I'm ok with visiting office during initial months to earn your respect and trust); - freedom in taking decisions; - time zone of Europe or Asia; - 1-2 interviews as a max, with tech specialists and managers. I am not interested in: - US time zone (I'd prefer morning shifts starting at 7am rather than coding till midnight); - strict "fabric" schedule like "9-to-6", "10-to-7", "11-to-8" and so on (since in IT this is an indicator of the unprofessional nature of the team and management); - jobs with a requirement of overall experience in software development of just a few years (I have 12, and the job offered should be my next challenge); - calls with HRs for "just to have a 30 minutes blah-blah-blah" (I have a prepared list of questions, and I hope you have prepared too); - if I have no word from you at any of the stages for more than a week - I am not more interested in the job; - I may consider test tasks only for tech lead or CTO roles, and it should be prepaid (for free you may have a look at my github and linkedin).
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \nWorked on a mobile application for tracking trips\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Worked on a mobile application for tracking trips

In [24]:
print("Original CVs:", df["CV"].notna().sum())
print("Clean CVs:", df["CV_Clean"].notna().sum())
print("Empty cleaned CVs:", (df["CV_Clean"] == "").sum())

Original CVs: 210250
Clean CVs: 210250
Empty cleaned CVs: 0

In [25]:
position_normalized = (
    df["Position"]
    .str.lower()
    .str.strip()
)

print("Original unique positions:", df["Position"].nunique())
print("After basic normalization:", position_normalized.nunique())

Original unique positions: 52913
After basic normalization: 47054

In [26]:
position_check = (
    df.groupby(position_normalized)["Position"]
    .unique()
)

duplicates = position_check[position_check.apply(len) > 1]

print("Normalized positions with multiple original forms:", len(duplicates))
print(duplicates.head(20))

Normalized positions with multiple original forms: 3803
Position
.net                                                                  [.Net, .NET]
.net architect                                    [.Net Architect, .NET Architect]
.net back-end developer          [.NET back-end developer, .NET Back-end develo...
.net backend developer           [.Net backend developer, .Net Backend develope...
.net c# developer                [.Net c# developer, .Net C# developer, .Net C#...
.net core back-end developer     [.Net Core back-end developer, .NET Core Back-...
.net core developer              [.Net Core Developer, .NET Core Developer, .NE...
.net developer                   [.net developer, .Net developer, .Net Develope...
.net developer (full stack)      [.NET developer (full stack), .NET Developer (...
.net developer (remote)          [.Net Developer (remote), .NET Developer (Remo...
.net developer remote               [.NET developer Remote, .NET Developer remote]
.net engineer                        [.Net Engineer, .NET engineer, .NET Engineer]
.net full stack developer        [.Net Full stack Developer, .Net Full Stack De...
.net full stack engineer         [.Net Full Stack Engineer, .NET Full Stack Eng...
.net full-stack developer        [.Net full-stack Developer, .Net Full-Stack De...
.net fullstack developer         [.NET Fullstack developer, .NET Fullstack Deve...
.net lead/architect                     [.Net Lead/Architect, .NET Lead/Architect]
.net senior software engineer    [.NET Senior software engineer, .NET Senior So...
.net software developer          [.Net Software developer, .Net Software Develo...
.net software engineer           [.Net software engineer, .Net Software Enginee...
Name: Position, dtype: object

In [27]:
df["Position_Clean"] = (
    df["Position"]
    .str.lower()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print(df[["Position", "Position_Clean"]].head(10))

                                            Position  \
0  13 years of exp || Solidity, C#, JavaScript ||...
1                                       1c Developer
2                                       1C developer
3                                       1C Developer
4                     #1 Customer Support Specialist
5                       1st/2nd Line Support Analyst
6                                1st line IT support
7                                       1С Developer
8  2-3D Аниматор в блендере, ГеймДизайнер, Режисс...
9                                              2D\3D

                                      Position_Clean
0  13 years of exp || solidity, c#, javascript ||...
1                                       1c developer
2                                       1c developer
3                                       1c developer
4                     #1 customer support specialist
5                       1st/2nd line support analyst
6                                1st line it support
7                                       1с developer
8  2-3d аниматор в блендере, геймдизайнер, режисс...
9                                              2d\3d

In [28]:
position_lengths = df["Position_Clean"].str.len()

print(position_lengths.describe())

print("\nPositions longer than 100 characters:")
print((position_lengths > 100).sum())

print("\nExamples:")
print(df.loc[position_lengths > 100, ["Position", "Position_Clean"]].head(10))

count    210250.000000
mean         22.122331
std          12.195696
min           1.000000
25%          15.000000
50%          19.000000
75%          25.000000
max         254.000000
Name: Position_Clean, dtype: float64

Positions longer than 100 characters:
326

Examples:
                                               Position  \
1903  3D Environment Artist, 3D Level Artist, 3D Art...
2026  5+ y. of experience in DS/ML, 5500$ : Senior D...
2027  8+ years as a Digital Marketing and Content St...
2604  Account manager, Sales Lead, Business developm...
3208  Amazon Consultant & eCommerce Marketplace Mana...
4980  Android developer | Kotlin engineer | Monetizi...
5902  Architect / Lead / Full Stack / Front end / Ba...
6223  Assistant Media Buyer, Media Buyer, Support-ju...
8332  Backend Developer | Senior | PHP [Laravel,Symf...
9215  Billing manager, billing account manager, bill...

                                         Position_Clean
1903  3d environment artist, 3d level artist, 3d art...
2026  5+ y. of experience in ds/ml, 5500$ : senior d...
2027  8+ years as a digital marketing and content st...
2604  account manager, sales lead, business developm...
3208  amazon consultant & ecommerce marketplace mana...
4980  android developer | kotlin engineer | monetizi...
5902  architect / lead / full stack / front end / ba...
6223  assistant media buyer, media buyer, support-ju...
8332  backend developer | senior | php [laravel,symf...
9215  billing manager, billing account manager, bill...

In [29]:
print("Positions with 1 character:", (position_lengths == 1).sum())
print("Positions with <= 3 characters:", (position_lengths <= 3).sum())

print("\nExamples:")
print(df.loc[position_lengths <= 3, ["Position", "Position_Clean"]].head(30))

Positions with 1 character: 1
Positions with <= 3 characters: 811

Examples:
     Position Position_Clean
823        3d             3d
824        3D             3d
3164       AI             ai
5591      Any            any
5592      Any            any
5682      aqa            aqa
5683      aqa            aqa
5684      AQA            aqa
5685      AQA            aqa
5686      AQA            aqa
5687      AQA            aqa
5688      AQA            aqa
5689      AQA            aqa
5690      AQA            aqa
5691      AQA            aqa
5692      AQA            aqa
5693      AQA            aqa
5694      AQA            aqa
5695      AQA            aqa
5696      AQA            aqa
5697      AQA            aqa
5698      AQA            aqa
6091      ASO            aso
7662       BA             ba
7663       BA             ba
7664       BA             ba
7665       BA             ba
7666       BA             ba
7667       BA             ba
7668       BA             ba

In [30]:
print("Unique cleaned positions:", df["Position_Clean"].nunique())

print("\nTop 30 cleaned positions:")
print(df["Position_Clean"].value_counts().head(30))

Unique cleaned positions: 46835

Top 30 cleaned positions:
Position_Clean
front-end developer           8563
qa engineer                   8300
project manager               6711
junior qa engineer            4969
ui/ux designer                4343
java developer                3769
manual qa engineer            3641
junior front-end developer    3062
it recruiter                  2719
business analyst              2438
ux/ui designer                2400
python developer              2285
frontend developer            2054
.net developer                2028
product manager               1775
full stack web developer      1762
devops engineer               1751
senior software engineer      1725
software engineer             1694
ios developer                 1601
android developer             1589
graphic designer              1560
full stack developer          1557
data analyst                  1540
junior project manager        1534
php developer                 1517
react developer               1483
marketing manager             1430
senior qa engineer            1404
junior java developer         1369
Name: count, dtype: int64

In [31]:
original_counts = df["Position"].value_counts()
clean_counts = df["Position_Clean"].value_counts()

print("Unique positions before cleaning:", df["Position"].nunique())
print("Unique positions after cleaning:", df["Position_Clean"].nunique())

print("\nReduction in unique positions:",
      df["Position"].nunique() - df["Position_Clean"].nunique())

Unique positions before cleaning: 52913
Unique positions after cleaning: 46835

Reduction in unique positions: 6078

In [32]:
technical_terms = ["C#", "C++", ".NET", "JavaScript", "Node.js", "Python"]

for term in technical_terms:
    count = df["CV_Clean"].str.contains(
        term,
        case=False,
        regex=False
    ).sum()
    print(f"{term}: {count}")

C#: 9986
C++: 6948
.NET: 11609
JavaScript: 29966
Node.js: 10363
Python: 21275

In [33]:
english_counts = df["English Level"].value_counts(dropna=False)

print(english_counts)

English Level
upper           78146
intermediate    64915
fluent          43102
pre             18197
basic            5269
NaN               485
no_english        136
Name: count, dtype: int64

In [34]:
print(df["Experience Years"].describe())

print("\nMissing values:", df["Experience Years"].isna().sum())

print("\nExperience distribution:")
print(df["Experience Years"].value_counts().sort_index())

count    210250.000000
mean          3.836901
std           3.291261
min           0.000000
25%           1.000000
50%           3.000000
75%           6.000000
max          11.000000
Name: Experience Years, dtype: float64

Missing values: 0

Experience distribution:
Experience Years
0.0     21461
0.5     15369
1.0     20635
1.5     11300
2.0     18966
2.5      9012
3.0     21510
4.0     18349
5.0     19650
6.0     11483
7.0      9137
8.0      7252
9.0      4195
10.0     5068
11.0    16863
Name: count, dtype: int64

In [35]:
experience_english = pd.crosstab(
    df["Experience Years"],
    df["English Level"]
)

print(experience_english)

English Level     basic  fluent  intermediate  no_english   pre  upper
Experience Years
0.0                1451    1650          8699          50  3534   5608
0.5                 855    1449          6363          11  2453   4237
1.0                 659    2799          8062          16  2377   6721
1.5                 371    1707          4262          10  1229   3718
2.0                 392    3524          6642          10  1720   6676
2.5                 149    1625          3119           3   738   3377
3.0                 300    4826          6545           8  1563   8267
4.0                 240    4217          5282           5  1136   7468
5.0                 248    4889          4931           4  1014   8564
6.0                 115    2985          2614           5   537   5225
7.0                 102    2585          1969           5   385   4091
8.0                  67    2073          1465           2   320   3324
9.0                  43    1235           818           0   164   1934
10.0                 57    1608           956           0   228   2219
11.0                220    5930          3188           7   799   6717

In [36]:
print("Unique Primary Keywords:", df["Primary Keyword"].nunique())

print("\nMissing Primary Keywords:",
      df["Primary Keyword"].isna().sum())

print("\nAll Primary Keywords:")
print(sorted(df["Primary Keyword"].dropna().unique()))

Unique Primary Keywords: 41

Missing Primary Keywords: 43

All Primary Keywords:
['.NET', 'Android', 'Artist', 'Business Analyst', 'C++', 'Data Analyst', 'Data Engineer', 'Data Science', 'Design', 'DevOps', 'Flutter', 'Golang', 'HR', 'Java', 'JavaScript', 'Lead', 'Lead Generation', 'Marketing', 'Node.js', 'Other', 'PHP', 'Product Manager', 'Project Manager', 'Python', 'QA', 'QA Automation', 'Recruiter', 'Ruby', 'Rust', 'SEO', 'SQL', 'Sales', 'Salesforce', 'Scala', 'Scrum Master', 'Security', 'Support', 'Sysadmin', 'Technical Writing', 'Unity', 'iOS']

In [37]:
print("Moreinfo unique:", df["Moreinfo"].nunique())
print("CV unique:", df["CV"].nunique())

print("\nMoreinfo examples:")
print(df["Moreinfo"].head(3).to_string())

print("\nCV examples:")
print(df["CV"].head(3).to_string())

Moreinfo unique: 210156
CV unique: 210250

Moreinfo examples:
0    Who am I:\r\n- 13 years of commercial experien...
1    Worked on a mobile application for tracking trips
2    1 am an 1C developer. I deployed an 1C to typo...

CV examples:
0    Landed a role of Director of Blockchain Develo...
1    \nWorked on a mobile application for tracking ...
2    \n1 am an 1C developer. I deployed an 1C to ty...

In [38]:
same_moreinfo_cv = (
    df["Moreinfo"].fillna("") == df["CV"].fillna("")
)

print("Exact same Moreinfo and CV:", same_moreinfo_cv.sum())
print("Different Moreinfo and CV:", (~same_moreinfo_cv).sum())

Exact same Moreinfo and CV: 0
Different Moreinfo and CV: 210250

In [39]:
df["CV_Word_Count"] = df["CV_Clean"].str.split().str.len()

print(df["CV_Word_Count"].describe())

count    210250.000000
mean        138.170740
std          98.551079
min           1.000000
25%          67.000000
50%         110.000000
75%         181.000000
max        1061.000000
Name: CV_Word_Count, dtype: float64

In [45]:
shortest_cvs = df.nsmallest(20, "CV_Word_Count")

print(
    shortest_cvs[
        ["Position", "CV_Word_Count", "CV_Clean"]
    ].to_string(index=False)
)

                            Position  CV_Word_Count                     CV_Clean
                         Программист              1                         well
           Computer Systems Engineer              2                    very good
                                  DA              2               experienced in
                      Data Scientist              2                     6 months
                Javascript Developer              2              resume attached
              QA Automation Engineer              2           Automation Testing
                         QA Engineer              2               manual testing
                              Rigger              2                Rigger middle
                   Android Developer              3 Develop android applications
                   Android Developer              3              Switch from Php
                        Data analyst              3              described in cv
DevSecOps, Cyber Security Specialist              3                   check CV .
                                done              3               done done done
                  Frontend Developer              3           ready for rolocate
 Junior iOS, Ruby on Rails Developer              3       ruby, swift codereview
                      .Net Developer              3                   Ask for CV
                    PHP/JS Developer              3         10.2019 - maybeworks
                    Product Designer              3        Lead Product Designer
                     Project Manager              3        project, manager, PMP
                    Python Developer              3           Python No gambling

In [47]:
longest_cvs = df.nlargest(20, "CV_Word_Count")

print(
    longest_cvs[
        ["Position", "CV_Word_Count", "CV_Clean"]
    ].to_string(index=False)
)

                                                                                                                                                                                                                           Position  CV_Word_Count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           CV_Clean
                                                                                                                                                                                  Strong middle/Senior .NET/JS full-stack developer           1061                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    - built multiple plugins for different Autodesk desktop products from the ground up that allowed my employer to save a huge amount of man-hours in our structural engineering department. - greatly expanded the functionality of existing company desktop products (construction management software) and greatly boosted the performance of existing tools by implementing proper multithreading and optimizing DB-related code and procedures. - designed and implemented a new complex web app for my previous company from scratch with a separate identity server, multilingual responsive UI, mobile devices support, offline work support (PWA with an advanced customizable caching system using browser's IndexedDB), and much more. - developed custom model geometry exporters for Autodesk BIM software to GLB/GLTF and IFC formats from scratch that solved a problem that our software was tied to proprietary model formats. - created a custom viewer for industrial 3D models with user interaction support, customizable HUD, and decent performance on huge scenes. Embedded the viewer to the company apps (web and desktop) so their clients can view construction 3D models without buying third-party software. - built a new specification-compliant viewer for PDF files available for web and desktop apps. It is based on PDF.js and uses complex custom logic built from the ground up to support adding and editing annotations of different types, which can be stored both inside the document and separately from it, which is still heavily used by my previous employer. - applied some huge optimization and refactoring to my current company's projects (web applications in the financial field) which led to a vast improvement in the performance of the applications allowing our customers to handle data from more clients in a much shorter time and without increasing the costs spent on hosting services. Also made some major code refactoring and implemented new functionality for their apps, both in the UI and the backend, related to data processing, report generation, user authentication, localization, and so much more. - helped our junior developers improve their skills and knowledge, and continually exchanged experience with my colleagues. - took an active part in PR reviews, team code reviews, designing projects' architecture. - vastly improved my English speaking skills by taking part in countless amount of meetings and discussions within the team and with the customers. Languages: - C# and JavaScript (mostly Typescript, actually): broad knowledge and considerable experience; the main languages I use at my current job; - Python and Java: basic knowledge and some non-commercial experience; used only in small pet projects; Platforms and frameworks: - .NET: creating reusable libraries with .NET Standard; programming new and expanding the existing desktop apps and plugins with .NET Framework + WPF; building web apps from scratch, also expanding and extensive refactoring of the existing ones using ASP.NET + EF (both Core and Framework versions). - Angular: building complex multi-modular single page and progressive web apps from the ground up, refactoring and expanding the existing ones; - Node.JS: programming console and web apps on a non-commercial basis using Express, Nest.JS; DBMS: - MSSQL: proficient; main DBMS I used at my jobs; created a lot of new functions and stored procedures for our projects and optimized even more; - PostgreSQL: used in a few small projects; - CosmosDB: practiced; have commercial experience working with it; - MongoDB: have a clear understanding but less experience; used it mostly in pet projects; - RedisDB: used in one of the company projects; Server technologies: IIS, Azure cloud services. I'm also familiar with: OOP, SOLID, design patterns, multithreading, async programming, API, REST, SPA, PWA, OAuth2/OpenID, SSO, Azure services (DevOps, web jobs, functions, blob storage, service bus), Docker, WebGL+GLSL, BIM, SCRUM, etc. Just some libs I have experience with: NPOI, OpenXML, IdentityServer, OpenIdDict, SignalR, CefSharp, EmbedIO, LiveCharts, Rollup, Karma, Jasmine, RxJS, jQuery, D3.js, Chart.js, Datatables.net, AgGrid, Three.js, PDF.js, and many others. English: B2. My commercial experience as a programmer began in May 2019. I started working in the IT department of a local company specializing in industrial construction design as a junior .NET developer. As a part of a team, I was working on a construction management software system, consisting of a few desktop apps, a web app, and a bunch of plugins for third-party software. I evolved into a middle full-stack .NET+JS dev and was the one trusted with the most difficult programming tasks we had. After the project left the active development stage I felt I was ready to move forward and found a job in another company, in which I continue to work as a full-stack developer within an experienced international team for foreign customers. I mainly focus on full-stack web programming, although interesting desktop or mobile projects are still good to go. I'm looking forward to working on challenging ambitious projects with positive people. Being a part of a multinational team primarily using English (like my current team is) would be great. Not interested in supporting old legacy applications using some obsolete technology stack. It's a sure way to stop evolving and lose further prospects, and I want to keep up with the times and face new challenges. I'm always ready to acquire new knowledge and skills as well as improve my existing ones. I'm generally interested in a long-term collaboration. However, some short-time though gripping projects are welcome. Remote employment is highly preferred. Life is too short to waste it in public transport or traffic jams. I will only accept an exceptional office job offer. Official employment and any help with a work visa in the EU country would be a huge plus as I'm not planning to return to Ukraine in the foreseeable future. I'm not a fan of any kind of obligatory team building or any similar group activities unrelated to my direct responsibilities. Being forced to attend any of these is a drawback for me. I also don't care about any 'sweeteners' like free cookies in the office or a free gym, as I won't use any of this anyway. I'm a self-taught software developer, who made his way into programming by spending lots of evenings and weekends learning stuff while having a demanding full-time job. If you are looking for a diploma, not for real skills, performance, and persistence, please save your time, I'm not your candidate. However, I'm ready to consider attending some educational courses to fill in this gap if it's beneficial for long-term cooperation with your company.

In [48]:
df.columns

Index(['Position', 'Moreinfo', 'Looking For', 'Highlights', 'Primary Keyword',
       'English Level', 'Experience Years', 'CV', 'CV_lang', 'id',
       '__index_level_0__', 'CV_Length', 'CV_Clean', 'Position_Clean',
       'CV_Word_Count'],
      dtype='str')

In [49]:
model_df = df[
    [
        "Position_Clean",
        "Moreinfo",
        "Looking For",
        "Highlights",
        "Primary Keyword",
        "English Level",
        "Experience Years",
        "CV_Clean",
        "CV_Word_Count"
    ]
].copy()

model_df.shape

(210250, 9)

In [50]:
model_df.isna().sum()

Position_Clean           0
Moreinfo                 0
Looking For         108195
Highlights          104721
Primary Keyword         43
English Level          485
Experience Years         0
CV_Clean                 0
CV_Word_Count            0
dtype: int64

In [51]:
pd.crosstab(
    model_df["Looking For"].isna(),
    model_df["Highlights"].isna()
)

Highlights   False  True
Looking For
False        71640  30415
True         33889  74306

In [52]:
model_df.dtypes

Position_Clean          str
Moreinfo                str
Looking For             str
Highlights              str
Primary Keyword         str
English Level           str
Experience Years    float64
CV_Clean                str
CV_Word_Count         int64
dtype: object

In [53]:
text_columns = [
    "Looking For",
    "Highlights",
    "Primary Keyword",
    "English Level"
]

for col in text_columns:
    model_df[col] = model_df[col].fillna("")

model_df.isna().sum()

Position_Clean      0
Moreinfo            0
Looking For         0
Highlights          0
Primary Keyword     0
English Level       0
Experience Years    0
CV_Clean            0
CV_Word_Count       0
dtype: int64

In [54]:
model_df["Primary Keyword"].value_counts()

Primary Keyword
JavaScript           33980
QA                   25089
Design               15068
Project Manager      12499
Java                 11463
.NET                  9388
Marketing             8984
Python                7588
PHP                   6947
QA Automation         5756
Other                 5395
Node.js               4896
Recruiter             4865
HR                    4776
Support               4597
Business Analyst      4431
DevOps                4120
Product Manager       4048
Sales                 3784
iOS                   3200
Android               3087
C++                   2981
Data Science          2571
Artist                2542
Lead                  2373
Data Analyst          2271
Unity                 1815
Sysadmin              1528
Ruby                  1380
Golang                1343
SQL                   1119
Flutter               1118
SEO                    875
Data Engineer          803
Lead Generation        799
Security               781
Technical Writing      687
Salesforce             380
Scala                  364
Scrum Master           356
Rust                   160
                        43
Name: count, dtype: int64

In [55]:
model_df["English Level"].value_counts()

English Level
upper           78146
intermediate    64915
fluent          43102
pre             18197
basic            5269
                  485
no_english        136
Name: count, dtype: int64

In [56]:
model_df["Position_Clean"].value_counts().head(30)

Position_Clean
front-end developer           8563
qa engineer                   8300
project manager               6711
junior qa engineer            4969
ui/ux designer                4343
java developer                3769
manual qa engineer            3641
junior front-end developer    3062
it recruiter                  2719
business analyst              2438
ux/ui designer                2400
python developer              2285
frontend developer            2054
.net developer                2028
product manager               1775
full stack web developer      1762
devops engineer               1751
senior software engineer      1725
software engineer             1694
ios developer                 1601
android developer             1589
graphic designer              1560
full stack developer          1557
data analyst                  1540
junior project manager        1534
php developer                 1517
react developer               1483
marketing manager             1430
senior qa engineer            1404
junior java developer         1369
Name: count, dtype: int64

In [57]:
model_df["Candidate_Text"] = (
    model_df["CV_Clean"] + " " +
    model_df["Moreinfo"] + " " +
    model_df["Looking For"] + " " +
    model_df["Highlights"]
).str.replace(r"\s+", " ", regex=True).str.strip()

model_df["Candidate_Text"].head()

0    Landed a role of Director of Blockchain Develo...
1    Worked on a mobile application for tracking tr...
2    1 am an 1C developer. I deployed an 1C to typo...
3    Perfect knowledge of 1C:Enterprise Platform. G...
4    thousands of resolved problems, also, thousand...
Name: Candidate_Text, dtype: str

In [58]:
model_df["Candidate_Text_Word_Count"] = (
    model_df["Candidate_Text"].str.split().str.len()
)

model_df["Candidate_Text_Word_Count"].describe()

count    210250.000000
mean        276.341479
std         197.102158
min           2.000000
25%         134.000000
50%         220.000000
75%         362.000000
max        2122.000000
Name: Candidate_Text_Word_Count, dtype: float64

In [59]:
model_df["Candidate_Text_Raw"] = model_df["Candidate_Text"]

model_df[["Candidate_Text_Raw", "Candidate_Text"]].head()

,Candidate_Text_Raw,Candidate_Text
0,Landed a role of Director of Blockchain Develo...,Landed a role of Director of Blockchain Develo...
1,Worked on a mobile application for tracking tr...,Worked on a mobile application for tracking tr...
2,1 am an 1C developer. I deployed an 1C to typo...,1 am an 1C developer. I deployed an 1C to typo...
3,Perfect knowledge of 1C:Enterprise Platform. G...,Perfect knowledge of 1C:Enterprise Platform. G...
4,"thousands of resolved problems, also, thousand...","thousands of resolved problems, also, thousand..."

In [60]:
technical_terms = ["C++", "C#", ".NET", "JavaScript", "Node.js", "Python"]

{
    term: model_df["Candidate_Text"].str.contains(
        term,
        case=False,
        regex=False
    ).sum()
    for term in technical_terms
}

{'C++': np.int64(6948),
 'C#': np.int64(9986),
 '.NET': np.int64(11609),
 'JavaScript': np.int64(29966),
 'Node.js': np.int64(10363),
 'Python': np.int64(21275)}

In [61]:
model_df["Candidate_Text_NLP"] = (
    model_df["Candidate_Text"]
    .str.lower()
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

model_df["Candidate_Text_NLP"].head()

0    landed a role of director of blockchain develo...
1    worked on a mobile application for tracking tr...
2    1 am an 1c developer. i deployed an 1c to typo...
3    perfect knowledge of 1c:enterprise platform. g...
4    thousands of resolved problems, also, thousand...
Name: Candidate_Text_NLP, dtype: str

In [62]:
model_df["Candidate_Text_NLP"].nunique()

210250

In [63]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5
)

X_tfidf_sample = tfidf.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

X_tfidf_sample.shape

(5000, 5000)

In [64]:
features = tfidf.get_feature_names_out()

features[:100]

array(['000', '01', '02', '02 2022', '03', '04', '05', '06', '06 2022',
       '07', '08', '09', '09 2020', '10', '10 years', '100', '100k', '11',
       '12', '12 years', '14', '15', '15 years', '16', '18', '19', '1c',
       '20', '200', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2018 2019', '2018 to', '2019',
       '2019 to', '2020', '2020 present', '2020 to', '2021', '2021 2022',
       '2021 may', '2021 present', '2021 to', '2022', '2022 present',
       '2022 to', '2023', '2023 present', '21', '23', '24', '25', '2d',
       '2d 3d', '2d and', '2d animation', '2d animator', '2d art',
       '2d artist', '2d graphics', '30', '300', '3d', '3d and',
       '3d animation', '3d animator', '3d art', '3d artist', '3d assets',
       '3d character', '3d characters', '3d coat', '3d design',
       '3d designer', '3d environment', '3d game', '3d generalist',
       '3d graphics', '3d max', '3d model', '3d modeler', '3d modeling',
       '3d modelling', '3d models', '3d motion', '3d painter',
       '3d printing', '3d software', '3d visualization', '3d visualizer',
       '3ds', '3ds max'], dtype=object)

In [65]:
import pandas as pd

feature_stats = pd.DataFrame({
    "feature": tfidf.get_feature_names_out(),
    "idf": tfidf.idf_
})

feature_stats.sort_values("idf", ascending=False).head(30)

                  feature       idf
198                   aem  7.119498
4990                   yr  7.032487
2876                  mos  6.952444
3318                   pe  6.878336
2629             listings  6.878336
2486              jewelry  6.878336
279                   aml  6.878336
1555             duration  6.878336
2520             keywords  6.878336
3540  project description  6.878336
3932                  she  6.809343
4691    used technologies  6.809343
2197                  icp  6.809343
2187         https github  6.809343
545           android dev  6.744804
677       artcraft school  6.744804
3047                odesa  6.744804
2018           github com  6.744804
772                 azure  6.744804
4618             turnover  6.684180
3848           scientific  6.684180
4440         this company  6.684180
2848  modelling texturing  6.627021
866                   bot  6.627021
797           banking app  6.627021
793                  baku  6.627021
1380             dec 2021  6.627021
1150      computer vision  6.627021
4759                  vip  6.627021
4761                 visa  6.627021

In [66]:
model_df["Candidate_Text_NLP"] = (
    model_df["Candidate_Text_NLP"]
    .str.replace(r"https?://\S+|www\.\S+", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

model_df["Candidate_Text_NLP"].head()

0    landed a role of director of blockchain develo...
1    worked on a mobile application for tracking tr...
2    1 am an 1c developer. i deployed an 1c to typo...
3    perfect knowledge of 1c:enterprise platform. g...
4    thousands of resolved problems, also, thousand...
Name: Candidate_Text_NLP, dtype: str

In [67]:
model_df["Candidate_Text_NLP"] = (
    model_df["Candidate_Text_NLP"]
    .str.replace(
        r"\b\d{4}\b",
        " ",
        regex=True
    )
    .str.replace(
        r"\b\d+(?:\.\d+)?\s*(?:years?|yrs?|months?|mos?)\b",
        " ",
        regex=True
    )
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

model_df["Candidate_Text_NLP"].head()

0    landed a role of director of blockchain develo...
1    worked on a mobile application for tracking tr...
2    1 am an 1c developer. i deployed an 1c to typo...
3    perfect knowledge of 1c:enterprise platform. g...
4    thousands of resolved problems, also, thousand...
Name: Candidate_Text_NLP, dtype: str

In [68]:
tfidf_clean = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5
)

X_tfidf_clean_sample = tfidf_clean.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

X_tfidf_clean_sample.shape

(5000, 5000)

In [69]:
feature_stats_clean = pd.DataFrame({
    "feature": tfidf_clean.get_feature_names_out(),
    "idf": tfidf_clean.idf_
})

feature_stats_clean.sort_values("idf", ascending=False).head(30)

                           feature       idf
163                            aem  7.119498
3302                            pe  6.878336
2500                      keywords  6.878336
2467                       jewelry  6.878336
244                            aml  6.878336
2176                            id  6.878336
2610                      listings  6.878336
3527           project description  6.878336
1531                      duration  6.878336
3926                           she  6.809343
4693             used technologies  6.809343
2175                           icp  6.809343
3024                         odesa  6.744804
742                          azure  6.744804
516                    android dev  6.744804
648                artcraft school  6.744804
3842                    scientific  6.684180
4438                  this company  6.684180
4618                      turnover  6.684180
1124               computer vision  6.627021
2825           modelling texturing  6.627021
3052                    of content  6.627021
835                            bot  6.627021
762                           baku  6.627021
3731  responsibilities development  6.627021
4765                          visa  6.627021
3900                          sept  6.627021
4763                           vip  6.627021
4692                   used kotlin  6.627021
766                    banking app  6.627021

In [70]:
feature_counts = pd.DataFrame({
    "feature": tfidf_clean.get_feature_names_out(),
    "document_frequency": (X_tfidf_clean_sample > 0).sum(axis=0).A1
})

feature_counts.sort_values(
    "document_frequency",
    ascending=False
).head(30)

            feature  document_frequency
280             and                4583
2229             in                4142
3026             of                4020
4469             to                3631
1809            for                3612
4851           with                3515
4300            the                3461
1679     experience                2648
3138             on                2347
4915           work                2215
669              as                2126
2892             my                2115
2087           have                2041
4209           team                1870
3543       projects                1816
1451    development                1751
4939        working                1682
1913           from                1658
2963            new                1500
248              an                1485
3524        project                1475
508         android                1429
3965         skills                1423
2318         in the                1378
1688  experience in                1344
218              am                1262
3114         of the                1215
1390         design                1213
35               3d                1208
1086        company                1164

In [71]:
tfidf_stop = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    stop_words="english"
)

X_tfidf_stop_sample = tfidf_stop.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

print(X_tfidf_stop_sample.shape)

(5000, 5000)

In [72]:
features_stop = tfidf_stop.get_feature_names_out()

print(features_stop[:100])

['000' '01' '02' '03' '04' '05' '06' '07' '08' '09' '10' '10 000'
 '10 people' '10 years' '100' '100k' '11' '12' '13' '14' '15' '150' '16'
 '17' '18' '19' '1c' '1m' '1st' '20' '200' '21' '23' '24' '25' '2d'
 '2d 3d' '2d animation' '2d animator' '2d art' '2d artist' '2d character'
 '2d characters' '2d concept' '2d game' '2d graphics' '2d illustration'
 '2d illustrations' '2d render' '30' '300' '360' '3d' '3d 2d'
 '3d animation' '3d animator' '3d art' '3d artist' '3d artists'
 '3d assets' '3d character' '3d characters' '3d coat' '3d design'
 '3d designer' '3d environment' '3d game' '3d generalist' '3d graphic'
 '3d graphics' '3d max' '3d maya' '3d model' '3d modeler' '3d modeling'
 '3d modeller' '3d modelling' '3d models' '3d motion' '3d objects'
 '3d painter' '3d printing' '3d projects' '3d software' '3d visualization'
 '3d visualizations' '3d visualizer' '3dcoat' '3ds' '3ds max' '3dsmax'
 '3rd' '3rd party' '40' '400' '4d' '50' '500' '500k' '5m']

In [73]:
model_df["Candidate_Text_NLP"] = (
    model_df["Candidate_Text_NLP"]
    .str.replace(r"\b\d+\b", " ", regex=True)
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [74]:
print(model_df["Candidate_Text_NLP"].head())

0    landed a role of director of blockchain develo...
1    worked on a mobile application for tracking tr...
2    am an 1c developer. i deployed an 1c to typogr...
3    perfect knowledge of 1c:enterprise platform. g...
4    thousands of resolved problems, also, thousand...
Name: Candidate_Text_NLP, dtype: str

In [77]:
tfidf_final_test = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    stop_words="english"
)

X_tfidf_final_test = tfidf_final_test.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

print(X_tfidf_final_test.shape)

(5000, 5000)

In [79]:
features_final = tfidf_final_test.get_feature_names_out()

important_terms = [
    "python",
    "javascript",
    "java",
    "android",
    "3d",
    "1c",
    "computer vision",
    "machine learning",
    "data science",
    "azure",
    "c++",
    "c#",
    ".net",
    "node.js"
]

{
    term: any(term == feature for feature in features_final)
    for term in important_terms
}

{'python': True,
 'javascript': True,
 'java': True,
 'android': True,
 '3d': True,
 '1c': True,
 'computer vision': True,
 'machine learning': True,
 'data science': True,
 'azure': True,
 'c++': False,
 'c#': False,
 '.net': False,
 'node.js': False}

In [80]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_token_test = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    stop_words="english",
    token_pattern=r"(?u)\b[\w+#.]+\b"
)

X_token_test = tfidf_token_test.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

features_token_test = tfidf_token_test.get_feature_names_out()

{
    term: any(term == feature for feature in features_token_test)
    for term in important_terms
}

{'python': True,
 'javascript': True,
 'java': True,
 'android': True,
 '3d': True,
 '1c': True,
 'computer vision': True,
 'machine learning': True,
 'data science': True,
 'azure': True,
 'c++': False,
 'c#': False,
 '.net': False,
 'node.js': True}

In [81]:
technical_check = {
    term: model_df["Candidate_Text_NLP"].str.contains(
        term,
        case=False,
        regex=False
    ).sum()
    for term in ["C++", "C#", ".NET", "Node.js"]
}

technical_check

{'C++': np.int64(6948),
 'C#': np.int64(9986),
 '.NET': np.int64(11438),
 'Node.js': np.int64(10363)}

In [82]:
import re

test_text = """
Python developer with experience in C++, C#, .NET, Node.js,
JavaScript, 3D modeling, 1C and Machine Learning.
"""

tokens = re.findall(
    r"(?u)(?:[a-zA-Z]+\+\+|[a-zA-Z]+#|\.[a-zA-Z]+|[a-zA-Z]+\.[a-zA-Z]+|\w+)",
    test_text.lower()
)

tokens

['python',
 'developer',
 'with',
 'experience',
 'in',
 'c++',
 'c#',
 '.net',
 'node.js',
 'javascript',
 '3d',
 'modeling',
 '1c',
 'and',
 'machine',
 'learning']

In [83]:
from sklearn.feature_extraction.text import TfidfVectorizer

def technical_tokenizer(text):
    return re.findall(
        r"(?u)(?:[a-zA-Z]+\+\+|[a-zA-Z]+#|\.[a-zA-Z]+|[a-zA-Z]+\.[a-zA-Z]+|\w+)",
        text.lower()
    )

tfidf_final = TfidfVectorizer(
    tokenizer=technical_tokenizer,
    token_pattern=None,
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    stop_words="english"
)

X_tfidf_final = tfidf_final.fit_transform(
    model_df["Candidate_Text_NLP"].head(5000)
)

print(X_tfidf_final.shape)

(5000, 5000)

In [84]:
features_final = tfidf_final.get_feature_names_out()

{
    term: term in features_final
    for term in [
        "python",
        "javascript",
        "java",
        "android",
        "3d",
        "1c",
        "computer vision",
        "machine learning",
        "data science",
        "azure",
        "c++",
        "c#",
        ".net",
        "node.js"
    ]
}

{'python': True,
 'javascript': True,
 'java': True,
 'android': True,
 '3d': True,
 '1c': True,
 'computer vision': True,
 'machine learning': True,
 'data science': True,
 'azure': True,
 'c++': True,
 'c#': True,
 '.net': True,
 'node.js': True}

In [85]:
print("Rows:", len(model_df))
print("Features:", len(tfidf_final.get_feature_names_out()))
print("Matrix shape:", X_tfidf_final.shape)
print("Matrix type:", type(X_tfidf_final))

Rows: 210250
Features: 5000
Matrix shape: (5000, 5000)
Matrix type: <class 'scipy.sparse._csr.csr_matrix'>

In [86]:
X_tfidf_full = tfidf_final.transform(
    model_df["Candidate_Text_NLP"]
)

print("Matrix shape:", X_tfidf_full.shape)
print("Matrix type:", type(X_tfidf_full))

Matrix shape: (210250, 5000)
Matrix type: <class 'scipy.sparse._csr.csr_matrix'>

In [87]:
tfidf_final = TfidfVectorizer(
    tokenizer=technical_tokenizer,
    token_pattern=None,
    max_features=5000,
    ngram_range=(1, 2),
    min_df=5,
    stop_words="english"
)

X_tfidf_full = tfidf_final.fit_transform(
    model_df["Candidate_Text_NLP"]
)

print("Matrix shape:", X_tfidf_full.shape)
print("Matrix type:", type(X_tfidf_full))

Matrix shape: (210250, 5000)
Matrix type: <class 'scipy.sparse._csr.csr_matrix'>

In [88]:
features_full = tfidf_final.get_feature_names_out()

{
    term: term in features_full
    for term in [
        "python",
        "javascript",
        "java",
        "android",
        "3d",
        "1c",
        "computer vision",
        "machine learning",
        "data science",
        "azure",
        "c++",
        "c#",
        ".net",
        "node.js"
    ]
}

{'python': True,
 'javascript': True,
 'java': True,
 'android': True,
 '3d': True,
 '1c': True,
 'computer vision': True,
 'machine learning': True,
 'data science': True,
 'azure': True,
 'c++': True,
 'c#': True,
 '.net': True,
 'node.js': True}

In [89]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_sample = cosine_similarity(
    X_tfidf_full[:5],
    X_tfidf_full[:5]
)

similarity_sample

array([[1.        , 0.        , 0.00853437, 0.04803221, 0.05514161],
       [0.        , 1.        , 0.        , 0.00839212, 0.        ],
       [0.00853437, 0.        , 1.        , 0.44135298, 0.        ],
       [0.04803221, 0.00839212, 0.44135298, 1.        , 0.01474127],
       [0.05514161, 0.        , 0.        , 0.01474127, 1.        ]])

In [90]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    X_tfidf_full[0],
    X_tfidf_full[:100]
).flatten()

top_indices = similarities.argsort()[::-1][1:6]

pd.DataFrame({
    "Candidate_Index": top_indices,
    "Similarity": similarities[top_indices],
    "Position": model_df.iloc[top_indices]["Position_Clean"].values
})

,Candidate_Index,Similarity,Position
0,51,0.091229,2d/3d generalist / art lead
1,15,0.079221,2d/3d artist
2,53,0.063074,"2d, 3d lead animator/executive animation lead/..."
3,54,0.057142,2d/3d lead designer
4,24,0.056056,2d/3d artist

In [2]:
import os

os.makedirs("../data/processed", exist_ok=True)

model_df.to_parquet(
    "../data/processed/candidates_processed.parquet",
    index=False
)

print("Processed dataset saved successfully.")

NameError: name 'model_df' is not defined